name: mkdocs
on:
  push:
  pull_request:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings[python]
      - run: pip install black
      - run: mkdocs build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: mkdocs gh-deploy --force
